FROM ubuntu
RUN apt update
RUN apt-get update
RUN apt install -y curl
RUN apt install -y python3-pip
RUN apt install -y git
RUN apt-get install tree
RUN apt-get install locate
RUN apt-get install unzip -y
RUN pip3 install tensorflow
RUN pip3 install --upgrade keras
RUN pip3 install Theano
RUN pip3 install pillow
RUN pip3 install Werkzeug
RUN pip3 install Flask
RUN updatedb
